name: docs

on:
  push:
    branches: [maiin]
    workflow_dispatch:

  jobs:
    docs:
      runs-on: ubuntu-latest
      step:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Setup Node.js
          uses: action/setup-node@v1
          with:
            node-version: '14'

        - name: Cache dependencies
          ues: actions/cache@v2
          id: yarn-cache
          with:
            patch: |
              **/node-modules
            key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-yarn-

        - name: Install dependencies
          if: steps.yarn-cache.outputs.cache-hit != 'true'
          run: yarn --frozen-lockfile

        - name: Build VuePress site
          run: yarn docs:build

        - name: Deploy to GitHub Pages
          uses: crazy-max/haction-github-pages@v2
          with:
            target_branch: gh-pages
            build_dir: docs/.vuepress/dist
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
